spring.application.name=chmuryProjekt

spring.datasource.url=jdbc:postgresql://localhost:5432/chmury_projekt
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
