CREATE TABLE "songs" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                         "band" text NOT NULL,
                         "album" text NOT NULL,
                         "name" text NOT NULL
);

CREATE TABLE "comments" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                            "content" text NOT NULL,
                            "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
                            "id_song" BIGINT NOT NULL
);

ALTER TABLE "comments" ADD FOREIGN KEY ("id_song") REFERENCES "songs" ("id") DEFERRABLE INITIALLY IMMEDIATE;